export const testProductData = {
  status: 'success',
  data: {
    pre_order: {
      is_pre_order: false,
      available_date: null,
    },
    is_shoes: false,
    description:
      '1 Piece. One shoulder, bold cutout detail swimsuit with a cheeky cut bottom.\r\n\r\nMachine wash / Do not bleach / warm iron. 78% polyamide 22% Elastane / Lining: 90% Polyamide 10% Elastane.\r\n\r\nPolybag packaging.',
    fabrics: [
      {
        percent: '78',
        name: 'POLYAMIDE',
      },
      {
        percent: '22',
        name: 'ELASTANE',
      },
    ],
    is_broken_pack: true,
    brand: {
      id: 'AXB',
      name: 'BeWicked',
      web_name: 'bewicked',
      brand_image:
        'https://dc964uidi8qge.cloudfront.net/OSFile/OS/banners/vendor/BeWicked_logo_8.jpg',
      brand_logo:
        'https://dc964uidi8qge.cloudfront.net/OSFile/OS/banners/vendor/BeWicked_logo_2.jpg',
      fulfillment: {
        fulfillment: 'BEWICKED',
        free_shipping_amt: 250,
        city: 'Los Angeles',
        min_order_amount: 50,
        state: 'CA',
        id: 'BEWICKED',
      },
      contact: {
        address: '1020 Wilde Street  Los Angeles, CA 90021',
        fax: '',
        represent: 'Rocky Samorano',
        email: 'tech@bewickedusa.com',
        phone: '(213) 622-6467',
        name: 'BeWicked',
      },
      information: {
        is_paid_home: false,
        seo_title: 'BeWicked Wholesale Clothing | BeWicked Wholesale Apparel',
        store_policy:
          'Notice: During covid our order processing times are 1-5 business days.\r\n\r\nFree Shipping Offer:\r\nFree shipping is available for the USA only via UPS Ground. International orders will be billed for shipping.\r\n\r\nCancellation Policy:\r\nPlease submit any cancellation through the "Message" system of OrangeShine to us. Please provide contact information so that we may contact you if we have questions in regards to canceling your order. Every effort will be made to accommodate the cancellation of your order, providing your order has not been charged and/or shipped out. In the event that a cancellation was submitted, and your order was shipped out after, we will gladly refund the complete balance charged after the merchandise has been received back, including the shipping costs. However, if the cancellation was documented as received after the order was shipped, we will refund the merchandise after it has been returned minus the return shipping cost.\r\n\r\nBe Wicked Images Release Agreement\r\n\r\nBe Wicked will provide our images to you as long as the following conditions are agreed to without waiver in their use:\r\n\r\n1. No picture or image offered, used or shot by Be Wicked can be used for any other purpose than for the sale of Be Wicked merchandise.\r\n\r\n2. Any Be Wicked image must be presented in a tasteful manner.\r\n\r\n3. No Be Wicked image can be altered without our consent first. Image resizing does not apply to this condition.\r\n\r\n4. There are no other side agreements, understandings or representations for Be Wicked image usage other than what is outlined in this agreement.\r\n\r\n5. No Be Wicked image shall be linked to any pornography site or usage.\r\n\r\n6. Be Wicked at all times retains the rights to any and all Be Wicked images.',
        description:
          'BEWICKED Inc. launched in 2010 with a top sales force team and expertly skilled designers, and quickly became one of the leading designers and manufacturers in fashion lingerie, shapewear, accessories, and sleep wear. We supply our partners and clients with fashion-forward, quality products at an exceptional value, and our brand fosters international recognition for fashion, femininity, and excitement. We go above and beyond on every detail, ensuring high quality and a low price — the ideal for value.\r\n\r\nWhile bringing back the definition of value, we are also redefining the definition of sexy lingerie — we design, manufacture, and distribute fashion-forward pieces in a variety of styles for all shapes and sizes. BEWICKED features seasonal collections in intimates, fashion bras and panties, and shapewear that cater to all body shapes and sizes while keeping customers on point with the latest trends.',
        seo_description: '',
        copy_prevention: false,
        size_chart_list: [
          {
            table: [
              [
                'Size',
                'Small',
                'Medium',
                'Large',
                'X-Large',
                'S/M',
                'M/L',
                'L/XL',
                '1X/2X',
                '3X/4X',
                'O/S',
                'Queen',
              ],
              [
                'Dress Size',
                '4-6',
                '8-10',
                '12-14',
                '14-16',
                '4-8',
                '8-12',
                '12-16',
                '18-22',
                '24-28',
                '6-12',
                '18-24',
              ],
              [
                'Bust',
                '32-34',
                '34-36',
                '36-38',
                '38-40',
                '32-38',
                '34-38',
                '36-40',
                '40-44',
                '48-54',
                '32-38',
                '42-48',
              ],
              [
                'Waist',
                '23-25',
                '25-27',
                '27-29',
                '29-31',
                '23-27',
                '25-29',
                '28-31',
                '31-35',
                '37-44',
                '23-29',
                '35-39',
              ],
              [
                'Hip',
                '34-36',
                '36-38',
                '38-40',
                '40-42',
                '34-38',
                '36-40',
                '38-42',
                '42-46',
                '50-56',
                '34-40',
                '46-50',
              ],
              [
                'Cup',
                'A-B',
                'B-C',
                'C',
                'C',
                'A-B',
                'B-C',
                'C',
                'C',
                'DD',
                'A-C',
                'C-D',
              ],
            ],
            name: "Woman's Size Chart",
          },
        ],
        return_policy: {
          restocking_fee: '0',
          return_processing_day: '5',
          return_policy:
            'Returns of any type of merchandise will not be accepted without prior Authorization. Any unauthorized returns will be refused. Returns on intimates and swimwear will not be accepted.\r\n\r\nAll claims for damaged or incorrect goods or a discrepancy in quantities shipped must be reported within five business days after receipt of goods. We will not accept returns for any merchandise either worn, damaged in-store, and not in its original packaging. Approved returns will be repaired or replaced as appropriate. \r\n\r\nShould a style had been out of stock on certain sizes we will not accept requests later to return the remaining sizes for this reason.\r\n\r\nWe will not physically accept returns at this time. Please do not ship to us.\r\n\r\nIf you would like to make a return request or have any additional questions about our return policy, please contact us.',
        },
        price_range: 2,
        reviews: {
          backorder_rate: 0,
          po_drop_rate_with_unit: 'N/A',
          avg_shipping_days_with_unit: '1.42 days',
          po_processing_day_grade: 'N/A',
          sold_out_rate_with_unit: '14.18 %',
          avg_shipping_days: 1.42,
          sold_out_rate: 14.18,
          backorder_rate_with_unit: '0 %',
        },
        segment: 'WOMEN',
        manufacture: 'China, Taiwan',
      },
      url: '/bewicked/',
      joined_date: '2020-10-14T12:14:00',
      newly_joined: false,
      is_featured_product_sort: false,
      promotion: {
        minimum_order: 250,
        start_date: '2021-12-10T00:00:00',
        coupon_code: 'O5SF09H033ZR',
        discount_desc: 'Free Shipping',
        end_date: '2022-12-10T00:00:00',
      },
      order_review: {
        score: 3.9,
        count: 10,
      },
      brand_main_banners: [
        {
          banner:
            'https://dc964uidi8qge.cloudfront.net/OSFile/OS/banners/vendor/Bewicked_logo_6.jpg',
          desc1: '',
          desc2: '',
        },
      ],
      brand_reward_rate: 0,
    },
    min_broken_pack_order_qty: 1,
    is_vendor_blocked: false,
    grouped_items: [
      {
        id: '94024649',
        shoe_sizes: null,
      },
    ],
    style_name: 'Kennedy Swimsuit',
    id: '94024649',
    updated: '2022-02-25T16:46:00',
    category: {
      master: {
        display_group_order: 1,
        id: 8,
        name: 'SWIMWEAR',
        slug_name: 'swimwear',
      },
      sub: {
        name: 'ONE-PIECES',
        slug_name: 'swimwear-one-pieces',
      },
    },
    is_restock: false,
    created: '2022-07-11T22:19:00',
    brand_average_order_review: {
      vendor_id: 'AXB',
      five_star_percentage: 70,
      four_star_percentage: 0,
      three_star_percentage: 0,
      two_star_percentage: 10,
      one_star_percentage: 20,
      average_total_score: 78,
      average_product_quality: 70,
      average_shipping_time: 76,
      average_handling_shipping_fee: 80,
      average_communication: 76,
      count_review: 10,
    },
    restock_date: null,
    brand_category: {
      id: 15220,
      name: 'One Piece Swimwear',
    },
    is_active: true,
    badges: {
      sale: false,
      plus: false,
      pre_order: false,
    },
    pictures: {
      tiny: [
        'https://dc964uidi8qge.cloudfront.net/OSFile/OS/Pictures/202202/L/64969d5e-969d-11ec-849a-0626c5bd3ecf_L.jpg',
        'https://dc964uidi8qge.cloudfront.net/OSFile/OS/Pictures/202202/L/65d61a46-969d-11ec-849a-0626c5bd3ecf_L.jpg',
        'https://dc964uidi8qge.cloudfront.net/OSFile/OS/Pictures/202202/L/67972e7e-969d-11ec-849a-0626c5bd3ecf_L.jpg',
      ],
      medium: [
        'https://dc964uidi8qge.cloudfront.net/OSFile/OS/Pictures/202202/E/64969d5e-969d-11ec-849a-0626c5bd3ecf_E.jpg',
        'https://dc964uidi8qge.cloudfront.net/OSFile/OS/Pictures/202202/E/65d61a46-969d-11ec-849a-0626c5bd3ecf_E.jpg',
        'https://dc964uidi8qge.cloudfront.net/OSFile/OS/Pictures/202202/E/67972e7e-969d-11ec-849a-0626c5bd3ecf_E.jpg',
      ],
      large: [
        'https://dc964uidi8qge.cloudfront.net/OSFile/OS/Pictures/202202/Z/64969d5e-969d-11ec-849a-0626c5bd3ecf_Z.jpg',
        'https://dc964uidi8qge.cloudfront.net/OSFile/OS/Pictures/202202/Z/65d61a46-969d-11ec-849a-0626c5bd3ecf_Z.jpg',
        'https://dc964uidi8qge.cloudfront.net/OSFile/OS/Pictures/202202/Z/67972e7e-969d-11ec-849a-0626c5bd3ecf_Z.jpg',
      ],
    },
    size_chart: {
      pack: [1, 1, 1, 1, 1],
      size: ['XS', 'S', 'M', 'L', '1XL'],
      size_chart: {
        XS: 1,
        S: 1,
        M: 1,
        L: 1,
        '1XL': 1,
      },
      total: 5,
    },
    brand_style_number: '1973RWB',
    originality: 'CHINA',
    breadcrumbs: [
      {
        name: 'WOMEN',
        url: '/wholesale-fashion-clothing/all-styles',
        api_url: 'styles/women/all-styles',
      },
      {
        name: 'SWIMWEAR',
        url: '/wholesale-fashion-clothing/swimwear',
        api_url: 'styles/women/swimwear',
      },
      {
        name: 'ONE-PIECES',
        url: '/wholesale-fashion-clothing/swimwear/swimwear-one-pieces',
        api_url: 'styles/women/swimwear/swimwear-one-pieces',
      },
    ],
    colors: [
      {
        color_id: 'AXB_0155',
        image:
          'https://dc964uidi8qge.cloudfront.net/OSFile/OS/ColorSwatch/202202/757b5362-969d-11ec-849a-0626c5bd3ecf.jpg',
        item_id: '94024649',
        name: 'WHITE/RED/BLUE',
      },
    ],
    price: {
      regular_price: 19,
      sale_price: 0,
      is_sale: false,
      price: 19,
    },
  },
  message: null,
};
